name: CI & SonarCloud

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    name: Build & SonarCloud Scan
    runs-on: ubuntu-latest

    # Imagen oficial de Node (Debian) con bash incluido
    container:
      image: node:22

    steps:
      # 1) Clonar con historial completo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Instalar dependencias
      - name: npm install
        run: npm install --legacy-peer-deps

      # 3) Build de Next.js
      - name: npm run build
        run: npm run build

      # 4) Escaneo SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          # Directorio base de tu código (opcional si es el root)
          projectBaseDir: .
          # Pasamos explícitamente org y projectKey
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
        env:
          # Único token requerido para autenticarse en SonarCloud
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
